---
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
      - ruby/install-deps:
          key: gem-2
      - run:
          name: RSpec Tests
          command: |
            bundle exec rspec -f j --dry-run | jq -r '.examples[] | .file_path + ":" + (.line_number | tostring)' | circleci tests run --command ">files.txt xargs echo" --verbose --split-by=timings > files.txt #split-by=timings is optional
      - run:
          name: RSpec Tests
          command: |
            bundle exec rspec -f j --dry-run | jq -r '.examples[] | .file_path + ":" + (.line_number | tostring)' | circleci tests run --command="xargs bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml" --verbose --split-by=timings --test-selector=classname
      - store_test_results:
          path: ~/rspec/rspec.xml
      - store_artifacts:
          path: ~/files.txt
      - store_artifacts:
          path: ~/rspec/rspec.xml

workflows:
  test_build:
    jobs:
      - test
