---
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    parallelism: 4
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
      - ruby/install-deps:
          key: gem-2
      - run:
          name: RSpec split
          command: |
            test_files=($(circleci tests glob "spec/**/*_spec.rb" | circleci tests run --command="xargs echo" --verbose --split-by=timings))
            echo "======"
            echo "${test_files[@]}"
            echo "======"
            bundle exec rspec "${test_files[@]}" --profile 10 --format RspecJunitFormatter --out ~/rspec/rspec.xml --format progress

      - store_test_results:
          path: ~/rspec/rspec.xml

workflows:
  test_build:
    jobs:
      - test
